# Generated by Django 2.0.2 on 2018-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
