# Generated by Django 2.0.2 on 2018-05-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20180519_1348'),
    ]

    operations = [
    ]
